version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: system
    ports:
      - "1433:1433"
    volumes:
      - sqlserverdata:/var/opt/mssql
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P system -Q 'SELECT 1'"]
      interval: 10s
      timeout: 10s
      retries: 10

  patient-service:
    build: .
    container_name: patient-service
    ports:
      - "5000:5000"
    depends_on:
      sqlserver:
        condition: service_healthy
    environment:
        SPRING_DATASOURCE_URL: jdbc:sqlserver://sqlserver:1433;databaseName=your_db_name
        SPRING_DATASOURCE_USERNAME: sa
        SPRING_DATASOURCE_PASSWORD: system

volumes:
  sqlserverdata:
